### ISSUE TITLE
コメント

### ISSUE THREAD

**Issue by inushima** [aikms-maker/Tipsy-iOS13#1]
https://github.com/aikms-maker/Tipsy-iOS13/blob/master/Tipsy/Controllers/CalculatorViewController.swift#L48

Swiftの場合は、ロジック中の分岐を減らため、ifでnil判定をする代わりにguardを使ったOptionalのアンラップをすることが多いです。

```
    @IBAction func calculatePressed(_ sender: UIButton) {
        guard let bill = billTextField.text, let inputBill = Double(bill) else { return }
        let splitBill = inputBill * (1+tip) / splitNumber
        calcresult = String(format: "%.2f", splitBill)
        performSegue(withIdentifier: "goToResult", sender: self)
    }
```

JavaなどOptinalがない言語の場合は、ifによるnull判定を多用する必要があったのですがバグの温床になりやすかったため、Swiftなど新し目の言語ではOptinalの考え方が導入されて、アンラップをすることでロジック本体でnullを意識しなくてもよいように設計されています。

**Comment by inushima** [comment]
https://github.com/aikms-maker/Tipsy-iOS13/blob/master/Tipsy/Controllers/CalculatorViewController.swift#L57

こちらのコメント同様です。
https://github.com/aikms-maker/BMI-Calculator-iOS13/issues/1#issuecomment-1400023973

**Comment by aikms-maker** [comment]
上記2件の指摘対応しました
かくにんお願いいたします
https://github.com/aikms-maker/Tipsy-iOS13/pull/2

**Comment by aikms-maker** [comment]
対応完了したのでクローズします。
